import type { Metadata } from "next";
import Link from "next/link";
import { ArrowUpRight, BookOpen, Bike, CheckCircle2, ChevronRight, Coffee, Dumbbell, Laptop, Shirt, Sofa, Sparkles, Ticket, Wrench } from "lucide-react";

import { ListingCard } from "@/components/marketplace/listing-card";
import { createClient } from "@/lib/supabase/server";
import { getListings, getSavedListingIds } from "@/features/marketplace/queries";
import { LISTING_CATEGORIES } from "@/features/marketplace/constants";

export const metadata: Metadata = { title: "Everything your campus has. Everything you need.", description: "Buy, sell, rent, and discover useful things from students around your campus." };
const categoryIcons = [BookOpen, Laptop, Sofa, Coffee, Shirt, Bike, Dumbbell, Sparkles, Wrench, Ticket];

export default async function HomePage() {
  const supabase = await createClient();
  const [{ listings }, savedIds] = await Promise.all([getListings(supabase, { page: 1 }), getSavedListingIds(supabase)]);
  const featured = listings.slice(0, 4).map((listing) => ({ ...listing, isSaved: savedIds.has(listing.id) }));
  const leadListing = featured[0];
  const supportingListings = featured.slice(1);

  return <div className="pb-20 lg:pb-0">
    <section className="border-b border-border bg-[linear-gradient(120deg,hsl(36_33%_96%),hsl(29_70%_92%))]"><div className="mx-auto grid max-w-7xl gap-10 px-4 py-16 sm:px-6 sm:py-24 lg:grid-cols-[1fr_0.75fr] lg:items-end lg:px-8"><div><p className="mb-5 flex items-center gap-2 text-xs font-bold uppercase tracking-[0.2em] text-primary"><span className="size-2 rounded-full bg-primary" /> Your campus, in one place</p><h1 className="max-w-3xl font-display text-5xl font-extrabold leading-[0.98] tracking-[-0.05em] sm:text-7xl">Everything your campus has.<br /><span className="text-primary">Everything you need.</span></h1><p className="mt-7 max-w-xl text-base leading-7 text-muted-foreground sm:text-lg">A student marketplace for the things that make campus life work. Find them nearby, from people you can actually meet.</p><form action="/marketplace" className="mt-8 flex max-w-xl rounded-2xl border border-foreground/10 bg-card p-1.5 shadow-elevated"><label className="sr-only" htmlFor="home-search">Search your campus</label><input id="home-search" name="q" placeholder="What are you looking for?" className="min-w-0 flex-1 bg-transparent px-4 text-sm outline-none" /><button className="grid size-11 shrink-0 place-items-center rounded-xl bg-foreground text-background transition hover:bg-primary" aria-label="Search marketplace"><ArrowUpRight className="size-5" /></button></form><div className="mt-5 flex flex-wrap gap-2 text-xs font-semibold text-muted-foreground"><span>Try</span>{["textbooks", "cycle", "desk lamp", "calculator"].map((term) => <Link key={term} href={`/marketplace?q=${term}`} className="rounded-full border border-border bg-card px-3 py-1.5 transition hover:border-primary hover:text-primary">{term}</Link>)}</div></div><div className="relative hidden min-h-[310px] overflow-hidden rounded-[2rem] bg-foreground p-7 text-background lg:block"><div className="absolute -right-12 -top-12 size-56 rounded-full border-[32px] border-primary/80" /><div className="absolute bottom-0 right-8 h-2/3 w-1/2 rounded-t-full bg-primary/90" /><div className="relative flex h-full flex-col justify-between"><span className="text-7xl font-black leading-none text-primary">“</span><div><p className="font-display text-2xl font-bold leading-tight">The best stuff is already<br />a few minutes away.</p><p className="mt-4 text-sm text-background/60">Verified students · local handoffs · less scrolling</p></div></div></div></div></section>

    <section className="mx-auto max-w-7xl px-4 py-12 sm:px-6 lg:px-8"><div><p className="text-xs font-bold uppercase tracking-[0.2em] text-primary">Start here</p><h2 className="mt-2 font-display text-2xl font-bold tracking-tight">What do you want to do?</h2></div><div className="mt-6 grid grid-cols-2 gap-3 sm:grid-cols-4"><Link href="/marketplace" className="rounded-2xl bg-foreground p-5 text-background transition hover:-translate-y-1"><span className="text-3xl">↗</span><p className="mt-8 font-display font-bold">Buy something</p><p className="mt-1 text-xs text-background/60">Find a useful deal</p></Link><Link href="/sell" className="rounded-2xl border border-border bg-primary p-5 text-primary-foreground transition hover:-translate-y-1"><span className="text-3xl">+</span><p className="mt-8 font-display font-bold">Sell something</p><p className="mt-1 text-xs text-primary-foreground/70">Make space, make money</p></Link><Link href="/marketplace?sort=newest" className="rounded-2xl border border-border bg-card p-5 transition hover:-translate-y-1"><span className="text-3xl">✦</span><p className="mt-8 font-display font-bold">See what’s new</p><p className="mt-1 text-xs text-muted-foreground">Fresh on campus</p></Link><Link href="/saved" className="rounded-2xl border border-border bg-card p-5 transition hover:-translate-y-1"><span className="text-3xl">♡</span><p className="mt-8 font-display font-bold">Your saved list</p><p className="mt-1 text-xs text-muted-foreground">Keep tabs on finds</p></Link></div></section>

    <section className="border-y border-border bg-card"><div className="mx-auto max-w-7xl px-4 py-12 sm:px-6 lg:px-8"><div className="flex items-end justify-between"><div><p className="text-xs font-bold uppercase tracking-[0.2em] text-primary">Browse the campus</p><h2 className="mt-2 font-display text-3xl font-bold tracking-tight">Find your kind of useful.</h2></div><Link href="/marketplace" className="hidden items-center gap-1 text-sm font-bold sm:flex">All categories <ChevronRight className="size-4" /></Link></div><div className="mt-8 grid grid-cols-2 gap-x-3 gap-y-6 sm:grid-cols-5">{LISTING_CATEGORIES.slice(0, 10).map((category, index) => { const Icon = categoryIcons[index]; return <Link key={category} href={`/marketplace?category=${encodeURIComponent(category)}`} className="group flex items-center gap-3"><span className="grid size-11 shrink-0 place-items-center rounded-xl bg-muted transition group-hover:bg-primary group-hover:text-primary-foreground"><Icon className="size-5" /></span><span className="text-sm font-bold leading-tight">{category}</span></Link>; })}</div></div></section>

    <section className="mx-auto max-w-7xl px-4 py-14 sm:px-6 lg:px-8"><div className="flex items-end justify-between"><div><p className="text-xs font-bold uppercase tracking-[0.2em] text-primary">A good place to start</p><h2 className="mt-2 font-display text-3xl font-bold tracking-tight">Featured around campus</h2></div><Link href="/marketplace" className="flex items-center gap-1 text-sm font-bold">Explore all <ChevronRight className="size-4" /></Link></div>{leadListing ? <div className="mt-7 grid gap-5 lg:grid-cols-[1.2fr_0.8fr]"><div className="rounded-2xl border border-border bg-muted/40 p-3"><div className="mb-3 flex items-center justify-between px-2"><span className="text-xs font-bold uppercase tracking-[0.16em] text-primary">Editor’s pick</span><span className="text-xs text-muted-foreground">A useful find for student life</span></div><ListingCard listing={leadListing} /></div><div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-1">{supportingListings.map((listing) => <ListingCard key={listing.id} listing={listing} compact />)}</div></div> : <div className="mt-7 rounded-2xl border border-dashed border-border p-12 text-center"><CheckCircle2 className="mx-auto size-8 text-primary" /><p className="mt-4 font-display font-bold">Your campus is just getting started.</p><p className="mt-1 text-sm text-muted-foreground">Be the first to list something useful.</p><Link href="/sell" className="mt-5 inline-flex rounded-xl bg-primary px-4 py-2.5 text-sm font-bold text-primary-foreground">Create a listing</Link></div>}</section>

    {supportingListings.length > 0 ? <section className="border-t border-border"><div className="mx-auto max-w-7xl px-4 py-14 sm:px-6 lg:px-8"><div className="flex items-end justify-between"><div><p className="text-xs font-bold uppercase tracking-[0.2em] text-primary">Fresh from your campus</p><h2 className="mt-2 font-display text-3xl font-bold tracking-tight">Recently listed</h2></div><Link href="/marketplace?sort=newest" className="flex items-center gap-1 text-sm font-bold">See all <ChevronRight className="size-4" /></Link></div><div className="mt-7 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{supportingListings.map((listing) => <ListingCard key={listing.id} listing={listing} />)}</div></div></section> : null}

    <section className="mx-auto max-w-7xl px-4 pb-16 sm:px-6 lg:px-8"><div className="grid gap-4 rounded-[2rem] bg-accent p-7 text-accent-foreground sm:grid-cols-[1fr_auto] sm:items-center sm:p-10"><div><p className="text-xs font-bold uppercase tracking-[0.2em] opacity-70">Built for handoffs</p><h2 className="mt-2 max-w-xl font-display text-3xl font-bold tracking-tight">Less anonymous internet. More people from your campus.</h2></div><Link href="/about" className="inline-flex items-center gap-2 font-bold">Why UniDrop <ArrowUpRight className="size-4" /></Link></div></section>
  </div>;
}